In [5]:
import warnings
warnings.filterwarnings('ignore')
import sys
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


class XGB:
  def __init__(self,d):
    try:
      df=pd.read_csv(d)
      df=df.drop(['Id'],axis=1)
      df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)
      x=df.iloc[:,:-1]
      y=df.iloc[:,-1]
      self.x_train,self.x_test,self.y_train,self.y_test=train_test_split(x,y,test_size=0.2,random_state=42)
    except Exception as e:
      msg,typ,lin=sys.exc_info()
      print(f'{msg} {typ} {lin.tb_lineno}')
  def train(self):
    try:
      self.reg=XGBClassifier(n_estimators=5)
      self.reg.fit(self.x_train,self.y_train)
      print(confusion_matrix(self.y_train,self.reg.predict(self.x_train)))
      print(classification_report(self.y_train,self.reg.predict(self.x_train)))
      print(accuracy_score(self.y_train,self.reg.predict(self.x_train)))
    except Exception as e:
      msg,typ,lin=sys.exc_info()
      print(f'{msg} {typ} {lin.tb_lineno}')

  def test(self):
    try:
      print(confusion_matrix(self.y_test,self.reg.predict(self.x_test)))
      print(classification_report(self.y_test,self.reg.predict(self.x_test)))
      print(accuracy_score(self.y_test,self.reg.predict(self.x_test)))
    except Exception as e:
      msg,typ,lin=sys.exc_info()
      print(f'{msg} {typ} {lin.tb_lineno}')
  def check(self):
    try:
      sl = 1.4
      sw = 1.8
      pl = 0.04
      pw = 0.08
      if self.reg.predict([[sl,sw,pl,pw]])[0]==0:
        print('setosa')
      elif self.reg.predict([[sl,sw,pl,pw]])[0]==1:
        print(f'Versicolor')
      else:
        print(f'Verginica')
    except Exception as e:
      msg,typ,lin=sys.exc_info()
      print(f'{msg} {typ} {lin.tb_lineno}')
if __name__=="__main__":
  obj=XGB('/content/Iris.csv')
  obj.train()
  obj.test()
  obj.check()




[[40  0  0]
 [ 0 39  2]
 [ 0  1 38]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      0.95      0.96        41
           2       0.95      0.97      0.96        39

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

0.975
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0
setosa
